### ISSUE TITLE
Bug: Inverse Integer Overflow

### ISSUE THREAD

**Issue by HadetTheUndying** [Krutchen/SLMCLBA#1]
[18:07] Naglfar Hitbox LBA: 
Repaired by Criss Ixtar for -2147483648 damage

We need to make negative damage respect the same AT_CAP suggest turning AT_CAP into an absolute value.

**Comment by ThunderRahja** [comment]
Insert code into `listen` event immediately after `integer dmg` is assigned:
```lsl
if (atcap) // use atcap to limit repairs
{
    if (dmg < -atcap) dmg = -atcap;
}
else if (dmg < -maxhp) // use maxhp to limit repairs
{
    dmg = -maxhp;
}
```
`llAbs(-2147483648)` is known to return `-2147483648` and should not be used in this case.

**Comment by HadetTheUndying** [comment]
Understood thanks for the help.

**Comment by HadetTheUndying** [comment]
Just waiting on a Dread to approve the changes now.

Changes with Bad Formatting:
https://github.com/Krutchen/SLMCLBA/pull/3

**Comment by Krutchen** [comment]
I'M GONNA SHIT IN A BUCKET AND THROW IT AT YOU HADET
