### ISSUE TITLE
Lba Light Vehicles become immortal after recieving continued damage from the same owner after blacklisting?

### ISSUE THREAD

**Issue by crossexonar** [Krutchen/SLMCLBA#20]
The weird vehicles at ESC are causing immortal lba 2.3 vehicles instead of the intended behaviour of keeping vehicles off the highway.
Lol blacklist

**Comment by HadetTheUndying** [comment]
> The weird vehicles at ESC are causing immortal lba 2.3 vehicles instead of the intended behaviour of keeping vehicles off the highway. Lol blacklist

Can you add some `llOwnerSay` stuff to the the recent list and blacklist stuff so we can see what's happening here? My bet is it's the recent list stuff because those object "respawn" don't they?

**Comment by crossexonar** [comment]
nawh i just left the lba default and its sitll doing it.
die()
{
    llSleep(1);
    //PUT ALL EXPLODEY SHIT AND SITBASE KILLING HOOKS IN HERE!!!!!
    //llDie();
    hp=maxhp;
    handlehp();
}
Will do the ownersay in a moment

**Comment by crossexonar** [comment]
llOwnerSay(llList2CSV(recent));
    llOwnerSay(llList2CSV(proc));
    if(hp==0&&proc==[])die();
    
0d59276a-3229-4c84-a1a6-4d0e801baf57, e7e8094a-7b32-023e-0b3c-f0039f7fb8be, [ESC.] C4, 50, 49.641022, 2 //C4 Hit it
2 //Cars smashing into it
2
2
    //die(); Isnt triggering

**Comment by Krutchen** [comment]
line 244 - proc=llListReplaceList(proc,[0],pf,pf+5);
this is the culprit, fixing lol

**Comment by Krutchen** [comment]
This should be fixed now! See if you can break anything else.
